# Basic arguments
work_dir: '/home/klein/PURLS/work_dir/purls_{split_config}'

# Processor
gpus: 1
num_epoch: {num_epoch}

# Debug
seed: 5
eval_interval: 1

# Data
root: '/home/klein/PURLS/synse_resources'
root2: '/home/klein/PURLS/{data_root}'
dataset: 'shift_{split}_r{random_suffix}' # Path to the generated visual features
dataloader: '{dataloader}'
split: {split}
data_type: 'full'

# Model
model_name: 'purls'
lr: 1e-4
model_args:
  input_size: 256
  hidden_size: 512
  output_size: 100
  emb_dim: 512
  n_hidden_layers: 0

# Ablation
activate_train: True
test_p: False
resume: False 